# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: lily58_no_dongle_left
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: lily58_no_dongle_right
  - board: nice_nano_v2
    shield: lily58_dongle
    artifact-name: lily58_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_dongle_left
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lily58_dongle_right